### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Miracle-qi** [axopy/pytrigno#1]
You have done a  great work, and I want to know what data does the MCC get and What is the corresponding paper in IEEE Transactions on Neural Systems and Rehabilitation Engineering.

**Comment by ixjlyons** [comment]
Hi, thanks for reaching out. This repository is a convenience library for streaming data from the Trigno Control Utility (TCU) for the [Delsys Trigno EMG system](https://www.delsys.com/products/wireless-emg/). TCU is basically a small program that exposes the data from the EMG system to a TCP port, and pytrigno streams this data and makes it available as numpy arrays. [pymcc](https://github.com/ucdrascal/pymcc) provides the same interface for a Measurement Computing DAQ. I'll write a bit about the interface here, but it needs to be documented generally somewhere. The intent of both projects is to be middleware between different hardware devices and [AxoPy](https://github.com/ucdrascal/axopy), which is a package I'm still working on.

The IEEE paper is [here](https://ieeexplore.ieee.org/document/8320385/), and [pygesture](https://github.com/ixjlyons/pygesture/tree/master/pygesture) is the correct repository to look at for the actual code used in the experiments in that paper (you'll notice that most of the code in pytrigno and pymcc is contained there, as well as lots of GUI code, processing code, etc.). AxoPy is intended to be a more general-purpose and improved version of pygesture, but it's a work in progress as I said.

The [example script](https://github.com/ucdrascal/pytrigno/blob/2b2d8d5590935b7c5af81bcc2ced17ef2adf14e9/examples/check_trigno.py) shows how to use the library. You create an object representing the device, passing in parameters that specify things like sample rate, channels to use, samples per update, etc. You can then poll for a buffer of samples periodically. I usually create a separate thread that repeatedly requests data from the device and connect the incoming arrays of data to a callback in a graphical user interface program. In any case, this is basically how it works:

```python
import pytrigno

# local device with channels 0-15, 200 samples per update
# (10 Hz update rate with 2 kHz sample rate)
dev = pytrigno.TrignoEMG((0, 15), 200)
# tell the device to start recording
dev.start()
# request samples (blocking call!), `data` is a numpy array with shape (16, 200)
data = dev.read()
# shut down connection
dev.stop()
```

**Comment by Miracle-qi** [comment]
Hello! I am doing EMG signal processing work currently, and I want to save data and draw waveforms in real time. I try to understand your work，the axopy. However, it’s hard to me. I will be very grateful if you can give me some advice how to use Axopy. Thank you!

发送自 Windows 10 版邮件应用

发件人: Kenneth Lyons
发送时间: 2018年4月1日 11:56
收件人: ucdrascal/pytrigno
抄送: Qi Shuhao; Author
主题: Re: [ucdrascal/pytrigno] question (#1)

Hi, thanks for reaching out. This repository is a convenience library for streaming data from the Trigno Control Utility (TCU) for the Delsys Trigno EMG system. TCU is basically a small program that exposes the data from the EMG system to a TCP port, and pytrigno streams this data and makes it available as numpy arrays. pymcc provides the same interface for a Measurement Computing DAQ. I'll write a bit about the interface here, but it needs to be documented generally somewhere. The intent of both projects is to be middleware between different hardware devices and AxoPy, which is a package I'm still working on.
The IEEE paper is here, and pygesture is the correct repository to look at for the actual code used in the experiments in that paper (you'll notice that most of the code in pytrigno and pymcc is contained there, as well as lots of GUI code, processing code, etc.). AxoPy is intended to be a more general-purpose and improved version of pygesture, but it's a work in progress as I said.
The example script shows how to use the library. You create an object representing the device, passing in parameters that specify things like sample rate, channels to use, samples per update, etc. You can then poll for a buffer of samples periodically. I usually create a separate thread that repeatedly requests data from the device and connect the incoming arrays of data to a callback in a graphical user interface program. In any case, this is basically how it works:
import pytrigno

# local device with channels 0-15, 200 samples per update
# (10 Hz update rate with 2 kHz sample rate)
dev = pytrigno.TrignoEMG((0, 15), 200)
# tell the device to start recording
dev.start()
# request samples (blocking call!), numpy array with shape (16, 200)
data = dev.read()
# shut down connection
dev.stop()

**Comment by ixjlyons** [comment]
Closing this, since the question seems to be more about AxoPy. The docs there are still in rough shape, but I'm hoping to improve situation soon. Feel free to file an issue there if you're experiencing problems.
