### ISSUE TITLE
accelerometer data quality

### ISSUE THREAD

**Issue by sreschechtko** [axopy/pytrigno#3]
Have you had any issues with quality of accelerometer data captured via the TCU or analog inputs? The accelerometer data I've collected both ways seems extremely noisy/nonsensical, even though data obtained through Delsys' proprietary software (and whatever signal processing is under the hood) looks very nice -- just wondering if you've run across these issues at all when working with the Trigno system.

Thanks!

**Comment by ixjlyons** [comment]
I haven't noticed issues with it, but I also haven't tested the accelerometer functionality extensively (mostly used EMG). I suspect it's just that you're looking at the "orientation" output in the Delsys software. I can't remember if they state anywhere what they're doing to the raw signals to produce that data, but I would guess it's a Kalman filter. If you want to verify that the sensors (and this library) at least work, you could capture some data during a simple test: let a sensor sit stationary for a couple seconds, flip it over 180 degrees, and let it sit for a couple seconds again. The output isn't gravity compensated if I remember correctly, so you should see one axis flip sign in the middle of the test data.

**Comment by sreschechtko** [comment]
Thanks -- I should check that more carefully when I am back in the lab. I'm pretty sure I was reading what Delsys called accelerometer rather than orientation or heading, but I still wouldn't be surprised if there's some processing going on behind the scenes. My reads using this package also looked pretty noisy (almost like I was missing values or something), but maybe I should try reading from the IMU port rather than the low freq port.

**Comment by ixjlyons** [comment]
Ok, going to close this. If you find that the output actually is missing samples or something, let me know.
