### ISSUE TITLE
Data acquisition with PyTrigno

### ISSUE THREAD

**Issue by urigott** [axopy/pytrigno#5]
Hi,

Thank you for your work!

I'm trying to read data from Trigno EMG using pyTrigno. I am able to connect, and when I send commands I can see an activity on the TCU. However, the results are always an array of zeros, both when I use TrignoAccel or TrignoEMG. 

Any ideas what should I do differently?

this is the code i'm using:

`from pytrigno import TrignoAccel`
`t=TrignoAccel((0,48),samples_per_read=200)
`t.start()
`data=t.read()
`t.stop()
`print (data.shape, data.sum())`

and the result I get is:
(48, 200) 0.0

Thank you,
Uri

**Comment by ixjlyons** [comment]
The only thing I can think of is to make sure the sensors are on and paired with the base. I know the base will send zeros if the sensors aren't actively transmitting to it.

**Comment by urigott** [comment]
It seems that the problem was that I didn't change the data_port. After changing it I started receiving data. Thanks!

**Comment by ixjlyons** [comment]
Great, thanks for following up.
