### ISSUE TITLE
Data Loss Issue During Continuous EMG Recording

### ISSUE THREAD

**Issue by martaglezgarcia** [axopy/pytrigno#6]
Hello,

First of all, I want to say that this code is incredible! It's been a huge help for my research project, and I really appreciate your work on it.

I’m encountering an issue with continuous data recording. Specifically, I'm experiencing a periodic data loss of around 1.5 seconds every 35 seconds. I'm unsure what could be causing this. I’m currently reading 1 sample at a time, but I’ve also tried reading 3 samples at a time, and the issue persists.

Since I need to process the EMG data in real-time, this is becoming a significant problem for my project.

I would greatly appreciate any assistance or insights you can offer.

Thank you so much for your help! 🫶 

---
UPDATE WITH SOLUTION

The problem was that I was running my Python code in WSL2. The problem was solved when I run the program in Windows. I guess the issue was caused by the connection between Windows and WSL2.

**Comment by ixjlyons** [comment]
I haven't had access to Trigno hardware for quite some time now, but I can guess that 1-3 samples per request isn't enough for the Python side to keep up and some buffer either within the base unit firmware or the driver is overrunning. Could you try something more like 100-200 samples per read and see if it's still dropping data?

**Comment by martaglezgarcia** [comment]
Hi! Thanks for the quick reply. 

I tried reading 200 samples and this is a plot of the signal I get:

![emg](https://github.com/user-attachments/assets/04341cca-31fd-412c-84b8-1690d892afde)

I'm not getting 0 as before, but still have this weird periodic loss or delay in the data acquisition :(

**Comment by ixjlyons** [comment]
Sorry for not following up, but I'm really not sure what would cause that. Did you end up figuring it out?

Edit: never mind I just saw the update on the original post. Thanks for that. I would expect a WSL setup to work fine though.
